In [75]:
import numpy as np

In [76]:
a = np.array(3)
print("Number of dimensions:", a.ndim)
# a.dtype

Number of dimensions: 0


In [77]:
a = np.array([1, 2, 3, 4, 589])
print("Number of dimensions:", a.ndim)
# a.dtype

Number of dimensions: 1


In [78]:
a = np.array([[1,2,5432],[654,676,58]])
print("Number of dimensions:", a.ndim)
# a.dtype

Number of dimensions: 2


In [79]:
a = np.array([[23,345,11],[123,23,1]])
print("Number of dimensions:", a.ndim)

Number of dimensions: 2


In [80]:
a = np.array([[1,2,3],[2,3,5],[5,3,1]])
print("Number of dimensions:", a.ndim)

Number of dimensions: 2


In [81]:
#okay I guess I now understand how to create
#the 3D
a = np.array([[[1,2,3],[4,5,6],[900,432,345]],[[7,8,9],[10,11,12],[123,234,456]]])
print("Number of dimensions:", a.ndim)

Number of dimensions: 3


In [82]:
#Naa it's confusing.....
#Have to clarify this up
a = np.array([[[1,4,5],[123,43,23],[12,14,5],[34,24,2]],
              [[49,34,92],[5943,2443,542],[2342,52,5],[543,56,2]],
             [[543,554,1],[35,56,21],[532,45,54],[5543,2,4]]])
print("Number of dimensions:", a.ndim)

Number of dimensions: 3


In [83]:
a

array([[[   1,    4,    5],
        [ 123,   43,   23],
        [  12,   14,    5],
        [  34,   24,    2]],

       [[  49,   34,   92],
        [5943, 2443,  542],
        [2342,   52,    5],
        [ 543,   56,    2]],

       [[ 543,  554,    1],
        [  35,   56,   21],
        [ 532,   45,   54],
        [5543,    2,    4]]])

In [84]:
#Naa it's confusing.....
#Have to clarify this up
a = np.array([[[1,4,5],[123,43,23],[12,14,5],[34,24,2]],
              
              [[49,34,92],[5943,2443,542],[2342,52,5],[543,56,2]],
              
             [[543,554,1],[35,56,21],[532,45,54],[5543,2,4]]])
print("Number of dimensions:", a.ndim)

Number of dimensions: 3


In [85]:
a

array([[[   1,    4,    5],
        [ 123,   43,   23],
        [  12,   14,    5],
        [  34,   24,    2]],

       [[  49,   34,   92],
        [5943, 2443,  542],
        [2342,   52,    5],
        [ 543,   56,    2]],

       [[ 543,  554,    1],
        [  35,   56,   21],
        [ 532,   45,   54],
        [5543,    2,    4]]])

In [86]:
# #Naa it's confusing.....
# #Have to clarify this up
# a = np.array([
              
#               [[1,4,5],[123,43,23],[12,14,5],[34,24,2]],
              
#               [[49,34,92],[5943,2443,542],[2342,52,5],[543,56,2]],
              
#              [[543,554,1],[35,56,21],[532,45,54],[5543,2,4]],
             
#              [[543,554,1],[35,56,21],[532,45,54],[5543,2,4]]
             
#              ])
# print("Number of dimensions:", a.ndim)

In [87]:
a


array([[[   1,    4,    5],
        [ 123,   43,   23],
        [  12,   14,    5],
        [  34,   24,    2]],

       [[  49,   34,   92],
        [5943, 2443,  542],
        [2342,   52,    5],
        [ 543,   56,    2]],

       [[ 543,  554,    1],
        [  35,   56,   21],
        [ 532,   45,   54],
        [5543,    2,    4]]])

In [88]:
a.ndim

3

In [89]:
# # okay I am going to challenge myself to create a 4D array. That should at elast 
# # check as a milestoen for today

# a = np.array()


# print("Number of dimensions:", a.ndim)

In [90]:
# import numpy as np

# # Creating a 4D array with shape (2, 2, 4, 3)
# a = np.array([
                
#               [
#                   [[1, 4, 5], [123, 43, 23], [12, 14, 5], [34, 24, 2]],
#                [[49, 34, 92], [5943, 2443, 542], [2342, 52, 5], [543, 56, 2]]
#               ],

              
#               [
#                   [[543, 554, 1], [35, 56, 21], [532, 45, 54], [5543, 2, 4]],
#                [[543, 554, 1], [35, 56, 21], [532, 45, 54], [5543, 2, 4]]
#               ]
    
#              ])

# print(a)
# print("\nNumber of dimensions:", a.ndim)  # Output: 4


In [91]:
# # The above was generated by the AI so if I get it right?

# # Honestly I'm confused as f fr


# a = np.array([

#     [
#         [[],[],[],[]],
#         [[],[],[],[]]
#     ],

#     [
#         [[],[],[],[]],
#         [[],[],[],[]]
#     ]
    
# ])
# print("\nNumber of dimensions:", a.ndim)  # Output: 4


In [92]:
# # An attempt to create a 5D array


# a = np.array([

#     [
#         [[],[],[],[],[]],
#         [[],[],[],[],[]]
#     ],

#     [
#         [[],[],[],[],[]],
#         [[],[],[],[],[]]
#     ],

#     [
#         [[],[],[],[],[]],
#         [[],[],[],[],[]]
#     ]
    
# ])
# print("\nNumber of dimensions:", a.ndim)  # Output: 4


In [94]:
# Okay i think I'm seeing some skeleton of some sort


# One (1) Dimension
#        []




# Two  (2) Dimension
#      [
#         [It doesn't matter the number of lists in here, it still gives 2D impression] 
#      ]







# Three  (3) Dimension
#        [
#            [[]],
#            [[]],
#            [[]],
#            [[]]
#        ]







# Four   (4)  Dimension
            # ([
            
            #     [
            #         [[],[],[],[]],
            #         [[],[],[],[]]
            #     ],
            
            #     [
            #         [[],[],[],[]],
            #         [[],[],[],[]]
            #     ]
                
            # ])