In [3]:
import numpy as np

In [7]:
a = np.array([1,23])
print("Number of dimension", a.ndim)

Number of dimension 1


In [8]:
np.sum(a)

24

In [9]:
np.sum(a,axis=0)

24

In [10]:
a = np.array([
    [123,3,4],
    [1, 4,5]
])
print("Number of dimension", a.ndim)

Number of dimension 2


In [11]:
np.sum(a,axis=1)

array([130,  10])

In [12]:
a = np.array([
    [
        [[12,3,5],[7,8,3],[34,1,2],[4,2,1]]
    ],
    [
        [[1,1,1],[1,1,1],[1,1,1],[1,1,1]
    ]]
])
print("Number of dimension", a.ndim)

Number of dimension 4


In [13]:
np.sum(a)

94

In [15]:
a

array([[[[12,  3,  5],
         [ 7,  8,  3],
         [34,  1,  2],
         [ 4,  2,  1]]],


       [[[ 1,  1,  1],
         [ 1,  1,  1],
         [ 1,  1,  1],
         [ 1,  1,  1]]]])

In [14]:
np.sum(a,axis=0)

array([[[13,  4,  6],
        [ 8,  9,  4],
        [35,  2,  3],
        [ 5,  3,  2]]])

In [18]:
np.sum(a,axis=1)

array([[[12,  3,  5],
        [ 7,  8,  3],
        [34,  1,  2],
        [ 4,  2,  1]],

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]]])

In [19]:
np.sum(a,axis=0)

array([[[13,  4,  6],
        [ 8,  9,  4],
        [35,  2,  3],
        [ 5,  3,  2]]])

In [20]:
np.prod(a,axis=0)

array([[[12,  3,  5],
        [ 7,  8,  3],
        [34,  1,  2],
        [ 4,  2,  1]]])

In [21]:
np.prod(a,axis=1)

array([[[12,  3,  5],
        [ 7,  8,  3],
        [34,  1,  2],
        [ 4,  2,  1]],

       [[ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1],
        [ 1,  1,  1]]])

In [39]:
a = np.array([
    [123,3,4,7,8,9,10],
    [1, 6,5,12,20,30,40]
])
print("Number of dimension", a.ndim)

Number of dimension 2


In [40]:
a

array([[123,   3,   4,   7,   8,   9,  10],
       [  1,   6,   5,  12,  20,  30,  40]])

In [41]:
np.sum(a,axis=1)

array([164, 114])

In [42]:
np.sum(a,axis=0)

array([124,   9,   9,  19,  28,  39,  50])

In [43]:
np.prod(a,axis=1)

array([7439040, 8640000])

In [44]:
np.prod(a,axis=0)

array([123,  18,  20,  84, 160, 270, 400])

In [45]:
a[:,-1]

array([10, 40])

In [50]:
a[1]

array([ 1,  6,  5, 12, 20, 30, 40])

In [51]:
a[0]

array([123,   3,   4,   7,   8,   9,  10])

In [52]:
a[:,0]

array([123,   1])

In [56]:
a[:,0:3:2]

array([[123,   4],
       [  1,   5]])