<a href="https://colab.research.google.com/github/Si-kaR/Ai_Space/blob/main/Day_6_Lab_ENCODE_TRANSFORM_DATA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.impute import SimpleImputer
import pandas as pd

import numpy as np

In [ ]:
from numpy import array
from sklearn.preprocessing import LabelEncoder
# define example
data = ['warm','hot','cold','luke warm','hot','cold','warm']

In [ ]:
values = array(data)
print(values)

['warm' 'hot' 'cold' 'luke warm' 'hot' 'cold' 'warm']


In [ ]:
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[3 1 0 2 1 0 3]


In [ ]:
inverted = label_encoder.inverse_transform(integer_encoded)[4]
print(inverted)

Negative


In [ ]:
covid_result=['Positive','Negative','Positive','Negative','Negative',]

In [ ]:
# Now attemtping to Encode
# Display should be series
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(covid_result)


print(integer_encoded)

[1 0 1 0 0]


So our above is an array.
Change it to a series



In [ ]:
integer_to_series = integer_encoded

print(integer_to_series)

[1 0 1 0 0]


In [ ]:
series = pd.Series(integer_to_series)
print(series)

0    1
1    0
2    1
3    0
4    0
dtype: int64


Okay so  now you have a series.

Try it with the 1 0 1 0 0

Done

In [ ]:

###
df=pd.DataFrame({'A':[12.0,np.nan,16,18,19,np.nan],
                 'B':[np.nan,13,14,17,18,np.nan],
                 'C':[14,np.nan,7,8,9,11]})

In [ ]:
df

A     B     C
0  12.0   NaN  14.0
1   NaN  13.0   NaN
2  16.0  14.0   7.0
3  18.0  17.0   8.0
4  19.0  18.0   9.0
5   NaN   NaN  11.0

In [ ]:
## Drop all the rows with at least one missing value
##
df.dropna()

A     B    C
2  16.0  14.0  7.0
3  18.0  17.0  8.0
4  19.0  18.0  9.0

So dropna() has dropped all NaNs

In [ ]:
## Drops a row with all NaN in each column.
# so it'll delete  something like;
# 6. NaN  NaN   NaN
## However, because we don't have such a thing in our table nothing is being affected
df.dropna(how='all')

A     B     C
0  12.0   NaN  14.0
1   NaN  13.0   NaN
2  16.0  14.0   7.0
3  18.0  17.0   8.0
4  19.0  18.0   9.0
5   NaN   NaN  11.0

In [ ]:
df.dropna(how='any')

A     B    C
2  16.0  14.0  7.0
3  18.0  17.0  8.0
4  19.0  18.0  9.0

In [ ]:
df.dropna(how='any', inplace=True)

In [ ]:
df.fillna(method='ffill')

A     B    C
2  16.0  14.0  7.0
3  18.0  17.0  8.0
4  19.0  18.0  9.0