In [122]:
from sklearn.impute import SimpleImputer  # To replace missing values maybe as Nan
import pandas as pd
import numpy as np
from numpy import array
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [123]:
temperature_data_names = ['warm','hot','cold','luke warm','hot','cold','warm']

temperature_data_names

['warm', 'hot', 'cold', 'luke warm', 'hot', 'cold', 'warm']

In [124]:
#Label Encoding
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(temperature_data_names)
integer_encoded

array([3, 1, 0, 2, 1, 0, 3])

In [125]:
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
integer_encoded

array([[3],
       [1],
       [0],
       [2],
       [1],
       [0],
       [3]])

In [126]:
onehot_encoder = OneHotEncoder(sparse=False)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
onehot_encoded

/home/griphen/.local/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [127]:
print(onehot_encoded)

[[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [128]:
body_types = ['slim', 'petite', 'average', 'athletic', 'muscular', 'curvy', 'fat', 'curvy', 'muscular', 'athletic', 'average', 'petite', 'slim']
body_types

['slim',
 'petite',
 'average',
 'athletic',
 'muscular',
 'curvy',
 'fat',
 'curvy',
 'muscular',
 'athletic',
 'average',
 'petite',
 'slim']

In [129]:
body_type_encoder = LabelEncoder()
body_type_encoded = body_size_encoder.fit_transform(body_types)
body_type_encoded

array([6, 5, 1, 0, 4, 2, 3, 2, 4, 0, 1, 5, 6])

In [130]:
body_type_encoded = body_type_encoded.reshape(len(body_type_encoded), 1)
body_type_encoded

array([[6],
       [5],
       [1],
       [0],
       [4],
       [2],
       [3],
       [2],
       [4],
       [0],
       [1],
       [5],
       [6]])

In [131]:
bodytype_onehotEncoder = OneHotEncoder(sparse=False)
bodytype_onehotEncoded = bodytype_onehotEncoder.fit_transform(body_type_encoded)
bodytype_onehotEncoded

/home/griphen/.local/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [132]:
print(bodytype_onehotEncoded)

[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]


In [133]:
fruits = ['Apple', 'Banana', 'Cherry', 'Damsen', 'Cherry', 'Banana', 'Apple']
fruits

['Apple', 'Banana', 'Cherry', 'Damsen', 'Cherry', 'Banana', 'Apple']

In [134]:
fruit_label_encoder = LabelEncoder()
fruit_label_encoded = fruit_label_encoder.fit_transform(fruits)
fruit_label_encoded

array([0, 1, 2, 3, 2, 1, 0])

In [135]:
fruit_label_encoded = fruit_label_encoded.reshape(len(fruit_label_encoded), 1)
fruit_label_encoded

array([[0],
       [1],
       [2],
       [3],
       [2],
       [1],
       [0]])

In [136]:
fruit_onehot_encoder = OneHotEncoder(sparse=False)
fruit_onehot_encoded = fruit_onehot_encoder.fit_transform(fruit_label_encoded)
fruit_onehot_encoded

/home/griphen/.local/lib/python3.11/site-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]])

In [137]:
print(fruit_onehot_encoded)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [138]:
# our final go at OneHot and Label Encoding
growth = [
    'Birth',
    'Infancy',
    'Toddler',
    'Childhood',
    'Adolescence',
    'Adulthood',
    'Old Age',
    'Adulthood',
    'Adolescence',
    'Childhood',
    'Toddler',
    'Infancy',
    'Birth'
]


In [139]:
growth_label_encoder = LabelEncoder()
growth_label_encoded = growth_label_encoder.fit_transform(growth)
growth_label_encoded = growth_label_encoded.reshape(len(growth_label_encoded), 1)

growth_onehot_encoder = OneHotEncoder(sparse_output=False)
growth_onehot_encoded = growth_onehot_encoder.fit_transform(growth_label_encoded)

print(growth_onehot_encoded)

[[0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]]


In [140]:
#################################################################

# I caan say I have semi mastered it now, but now I have to become more familiar with the reverse as well

In [141]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[0, :])])
print(inverted)

['Birth']


In [142]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[1, :])])
print(inverted)

['Infancy']


In [143]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_label_encoded[2, :])])
print(inverted)

['Adolescence']


In [144]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[3, :])])
print(inverted)

['Childhood']


In [145]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[-2, :])])
print(inverted)

['Infancy']


In [146]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[-3, :])])
print(inverted)

['Toddler']


In [147]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[12, :])])
print(inverted)

['Birth']


In [148]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[:, 3])])
print(inverted)

['Childhood']


In [149]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[:, 1:3])])
print(inverted)

['Adulthood']


In [150]:
inverted = growth_label_encoder.inverse_transform([np.argmax(growth_onehot_encoded[:, :])])
print(inverted)

['Birth']


In [151]:
array =pd.DataFrame({'A':[12.0,np.nan,16,18,19,np.nan],
                 'B':[np.nan,13,14,17,18,np.nan],
                 'C':[14,np.nan,7,8,9,np.nan]})

In [152]:
array

A     B     C
0  12.0   NaN  14.0
1   NaN  13.0   NaN
2  16.0  14.0   7.0
3  18.0  17.0   8.0
4  19.0  18.0   9.0
5   NaN   NaN   NaN

In [158]:
drop_any = array.dropna(how='any')
drop_any


A     B    C
2  16.0  14.0  7.0
3  18.0  17.0  8.0
4  19.0  18.0  9.0

In [163]:
# if the row has content, we can use that as a guidepost to fill the rest
fill_porthole = array.fillna(method='bfill')
fill_porthole

/tmp/ipykernel_20860/3988782003.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  fill_porthole = array.fillna(method='bfill')


A     B     C
0  12.0  13.0  14.0
1  16.0  13.0   7.0
2  16.0  14.0   7.0
3  18.0  17.0   8.0
4  19.0  18.0   9.0
5   NaN   NaN   NaN

In [168]:
## We can fill a particular column as well, and with the mean

fill_some_column_B = array.B.fillna(value=np.mean(array.B))
fill_some_column_B

0    15.5
1    13.0
2    14.0
3    17.0
4    18.0
5    15.5
Name: B, dtype: float64

In [170]:
fill_column_C = array.C.fillna(value=np.mean(array.C))
fill_column_C

0    14.0
1     9.5
2     7.0
3     8.0
4     9.0
5     9.5
Name: C, dtype: float64

In [172]:
fill_column_A = array.A.fillna(value=np.mean(array.A))
fill_column_A

0       12.0
1    65664.0
2       16.0
3       18.0
4       19.0
5    65664.0
Name: A, dtype: float64

In [173]:
# Instead of mean we can use something else,,,,,,,,,,,,,like product, sum, etc

fill_column_A = array.A.fillna(value=np.product(array.A))
fill_column_A


# Product of 12, 16, 18, 19 will give 65664.0............showing that those were the areas with Nan

0       12.0
1    65664.0
2       16.0
3       18.0
4       19.0
5    65664.0
Name: A, dtype: float64

In [177]:
### Let's attempt making it show 404........thikn we can?

fill_A_404 = array.A.replace(value=404)

TypeError: 'regex' must be a string or a compiled regular expression or a list or dict of strings or regular expressions, you passed a 'bool'

In [182]:
fill_A_404 = array['A'].fillna(value=404)
fill_A_404

0     12.0
1    404.0
2     16.0
3     18.0
4     19.0
5    404.0
Name: A, dtype: float64

In [183]:
imp=SimpleImputer(strategy='median')

In [184]:
a=imp.fit_transform(array)

In [186]:
array=pd.DataFrame(a, columns=['A','B','C'])

In [187]:
array

A     B     C
0  12.0  15.5  14.0
1  17.0  13.0   8.5
2  16.0  14.0   7.0
3  18.0  17.0   8.0
4  19.0  18.0   9.0
5  17.0  15.5   8.5